apiVersion: apps/v1
kind: Deployment
metadata:
  name: dplydbapi
spec:
  replicas: 1
  selector:  # Selector de pods
    matchLabels:  # Localiza objetos con la etiqueta
      app: dbapi
  template:  # Define los pods
    metadata:
      labels:
        app: dbapi  # Nombre de los pods por este deploy
    spec:  # Especificaciones de los pods
      containers:
      - name: poddbapi
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "2424"
        - name: MYSQL_DATABASE
          value: "db_tec"

