apiVersion: apps/v1
kind: Deployment
metadata:
    name: webfront
spec:
    selector:
        matchLabels:
            app: webfrond
    replicas: 1
    template:
        metadata:
            labels: 
                app: webfrond
        spec:
            containers:
            - name: podfrond
              image: gio242424/frond
              ports:
              - containerPort: 82