apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfront
spec:
  selector:
    matchLabels:
      app: webfront
  replicas: 1
  template:
    metadata:
      labels: 
        app: webfront
    spec:
      containers:
      - name: podfront
        image: gio242424/frond
        ports:
        - containerPort: 82
