apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dplyapitec
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: podapi
        image: gio242424/k8s:v1
        ports:
        - containerPort: 80
