apiVersion: v1
kind: Service
metadata:
  name: srvdbapi
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3306   # Puerto en el servicio
      targetPort: 3306  # Puerto en el contenedor
      nodePort: 32000  #Puerto de salida
